### ISSUE TITLE
Storage missing piglin tag

### ISSUE THREAD

**Issue by WenXin20** [grim3212/AssortedStorage#1]
`Assorted Storage v2.1.0`
`Minecraft v1.16.4`
`Forge v35.1.28`

Gold safes and the golden multitool and hammer from assorted tools are missing the item tag `minecraft:piglin_loved`.
All storage blocks are missing the block tag `minecraft:guarded_by_piglins`.

**Comment by grim3212** [comment]
Alright everything should now be added to the missing piglin tags. Thanks for pointing it out!

**Comment by WenXin20** [comment]
No prob!

**Comment by WenXin20** [comment]
I just realized that the Gold Building Wands are also missing the `piglin_loved` tag.

**Comment by grim3212** [comment]
Good catch it Assorted Tools has been updated.
