### ISSUE TITLE
Fabric 1.19.4: Chest, Barrel, Shulker Box and Hopper recipes for all tiers (except stone) are broken

### ISSUE THREAD

**Issue by IulianDan** [grim3212/AssortedStorage#12]
Fabric Version: 0.14.19
Mod Version: 9.0.2 for Fabric
Assorted Core and Assorted Lib are installed and updated to latest version.

All recipes for chests, barrels, shulker boxes and hoppers, starting from copper tier and going up, are missing the middle component of the recipe (previous tier of item), making them all uncraftable:
![image](https://github.com/grim3212/AssortedStorage/assets/32518786/95430641-2311-4c5b-9c1a-a755ee0f4633)
![image](https://github.com/grim3212/AssortedStorage/assets/32518786/11e4200d-be16-4f8a-95a4-535cd77a79f5)
The only recipes that are working correctly are the stone version:
![image](https://github.com/grim3212/AssortedStorage/assets/32518786/b99dce81-6b71-450a-b3b6-d772b2d4c7d7)

Bag Recipes are unaffected:
![image](https://github.com/grim3212/AssortedStorage/assets/32518786/723f7426-e936-4ed1-9be5-8d54f7511158)

Here is a list of the mods I'm using: https://pastebin.com/1jx65pTv

I should also mention there are no errors in the console mentioning AssortedStorage, atleast as far as I can see.

**Comment by IulianDan** [comment]
I tested with only the essential mods, and the problem persists:
![image](https://github.com/grim3212/AssortedStorage/assets/32518786/acf06c0c-f787-4d1e-8234-24155aa20b87)

Mods:
  [✔] architectury-8.1.80-fabric
  [✔] assortedcore-fabric-1.19.4-8.0.0
  [✔] assortedlib-fabric-1.19.4-2.0.0
  [✔] assortedstorage-fabric-1.19.4-9.0.2
  [✔] assortedtech-fabric-1.19.4-7.0.2
  [✔] assortedtools-fabric-1.19.4-9.0.1
  [✔] cloth-config-10.0.96-fabric
  [✔] fabric-api-0.80.0+1.19.4
  [✔] modmenu-6.2.2
  [✔] rer-2.8.0
  [✔] RoughlyEnoughItems-11.0.597
  [✔] RoughlyEnoughProfessions-fabric-1.19.4-1.2.1
  [✔] roughly-searchable-2.5.3+1.19.4
The errors I got in the console:
https://pastebin.com/FGi5Fbh8

**Comment by grim3212** [comment]
Thanks for the report I was able to repro!

New versions are getting uploaded currently to fix the broken recipes.

Also those errors you saw in the console should only be the first time you run. They are more or less to indicate the config files were out of date. So unless you see them every time they can be ignored.
