### ISSUE TITLE
[Forge 1.20.1] Compacting Crate allows Sand duplication

### ISSUE THREAD

**Issue by medsal15** [grim3212/AssortedStorage#14]
Putting at least 4 sand in a compacting crate allows it to be retrieved as either sandstone or cut sandstone. If the crate is broken with the sand still inside, the player can get up to three times as much sand as they put in. It seems to convert the sandstone and cut sandstone back into 4 sand each.

The same issue also happens with red sandstone

**Comment by grim3212** [comment]
Thanks for the report. I think this should be fixed now with version 10.0.1. If you still have issues feel free to reopen. Thanks!
