### ISSUE TITLE
[Suggestion] Make locksmith keys compatible with Curious/Trinket

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [grim3212/AssortedStorage#15]
It would be really nice if you could make some items, for example the locksmith keys, compatbile with Curious. We would be able to wear the keys or the key bundle in a Curious slot.

**Comment by grim3212** [comment]
I like this idea 👍. It would save a slot which I definitely think is an improvement. 

Next time I have some time I will look into this.

**Comment by grim3212** [comment]
With the latest version 10.0.3 I have added support for both Curios and Trinkets.
