### ISSUE TITLE
Adding Doors that can be locked! (Sugg.)

### ISSUE THREAD

**Issue by SamhitApple** [grim3212/AssortedStorage#2]
As the title suggests, adding lockable doors would just be super cool! It would make this mod a vanilla-esque alternative to Security Craft which adds say lasers, plasma guns and all the other things that don't go into Vanilla pretty well. That's where this mod truly comes to the rescue!

**Comment by grim3212** [comment]
Hey, I agree that does sound like a good idea! Just uploaded a new version that allows you to be able to lock the vanilla doors as well as the Quartz Door from AssortedDecor. If you notice any issues please create another bug.

**Comment by SamhitApple** [comment]
Thank you! I'm gonna test it and give some feedback!

**Comment by grim3212** [comment]
Sounds good, the documentation for how to use it is here. [https://assortedmods.com/storage/locksmith#doors](https://assortedmods.com/storage/locksmith#doors)
