### ISSUE TITLE
Locksmith not working!

### ISSUE THREAD

**Issue by SamhitApple** [grim3212/AssortedStorage#4]
When I place down the locksmith and put the lock or key inside the right slot and type in the combination I want to set, the output slot is empty! Nothing happens!
**Log File:** https://pastebin.com/HbqgVaQx
**Image:** 
![Screenshot (141)](https://user-images.githubusercontent.com/76992008/104290925-f1bc7780-54e0-11eb-89cf-de8738f5ef36.png)

**Comment by grim3212** [comment]
You are completely right! Not sure how this snuck past me in the last update. 0f83150 fixes this and is in the latest version.

**Comment by SamhitApple** [comment]
Thanks for the quick fix!

**Comment by itsdinkd** [comment]
Locksmith is actually duping items. Can you please release this on curseforge? I operate my own modpack, and you cannot just put committed files into the pack and upload. Curseforge will deny the upload. 

![image](https://user-images.githubusercontent.com/35115304/155906914-78bcf7fd-02db-480a-a3c9-d4f4811e02ef.png)

**Comment by grim3212** [comment]
Yeah, that seems pretty bad. Should have a release out to fix this shortly.

**Comment by grim3212** [comment]
[d3b929b](https://github.com/grim3212/AssortedStorage/commit/d3b929b04aac1c01bf48346028ff93bc1161f29d) Fixes the dupe bug. Should be out with 4.1.1
