### ISSUE TITLE
Locked doors state is not sync between server and clients

### ISSUE THREAD

**Issue by VirtualGaming1** [grim3212/AssortedStorage#6]
the lock door state is not syncing between the server and clients

for example I have the key for the door but my friend dont and I open the door on my side and the server got that but on my friend side the door is closed.

**Comment by grim3212** [comment]
Which version is this on?

**Comment by grim3212** [comment]
Should now be fixed on the new 1.18.1 version the fixed were already available on the 1.18.2 version.
